baseURL = 'https://xiaoheshang404.github.io'
languageCode = 'zh-CN'
title = "Yedongxin's blog"
theme = 'archie'

copyright = "© Thomas Monaghan"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
pagination.pagerSize = 4

[params]
# favicon = ""
# og_image = ""
mode = "auto"
useCDN = true
subtitle = "writes about working with code"
description = "Tom Monaghan's blog on software engineering"

[[menu.main]]
name = "posts"
url = "/posts"
weight = 1

[[menu.main]]
name = "me"
url = "/me"
weight = 2

[privacy.googleAnalytics]
disable = true
respectDoNotTrack = true
